name: Build iOS App

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Package
    runs-on: macos-26

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Extract version
        run: |
          VERSION=$(awk -F'=' '/^[[:space:]]*VERSION[[:space:]]*=/ {gsub(/[[:space:]]/,"",$2); print $2; exit}' Config.xcconfig)
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Install Dependencies
        run: |
          set -e

          # Packages we desperately need
          brew install ldid dpkg libarchive

      - name: Setup LLVM Toolchain
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
          LLVM_RUN_ID: "29906841202"
        run: |
          set -e

          GH_REPO="ruri1208/LLVM-On-iOS"

          mkdir -p CoreCompiler/CoreCompilerSupportLibs

          if [ -n "$LLVM_RUN_ID" ]; then
            RUN_ID="$LLVM_RUN_ID"
            echo "Using specified workflow run: $RUN_ID"
          else
            RUN_ID=$(gh run list \
              --repo "$GH_REPO" \
              --status success \
              --limit 1 \
              --json databaseId \
              -q '.[0].databaseId')
            echo "Using latest successful workflow run: $RUN_ID"
          fi

          gh run download "$RUN_ID" \
            --repo "$GH_REPO" \
            -n "CoreCompilerSupportLibs" \
            --dir CoreCompiler/

          tar -xJ -f CoreCompiler/CoreCompilerSupportLibs.tar.xz -C CoreCompiler/
          rm CoreCompiler/CoreCompilerSupportLibs.tar.xz

          gh run download "$RUN_ID" \
            --repo "$GH_REPO" \
            -n "LLVM.xcframework" \
            --dir CoreCompiler/CoreCompilerSupportLibs/

          tar -xJ -f CoreCompiler/CoreCompilerSupportLibs/LLVM.xcframework.tar.xz -C CoreCompiler/CoreCompilerSupportLibs/
          rm CoreCompiler/CoreCompilerSupportLibs/LLVM.xcframework.tar.xz

          rm -rf Shared/SwiftToolchain

      - name: Build Nyxian
        timeout-minutes: 1200
        run: |
          set -e

          CHECK_DEPS=0 make all

      - name: Upload Nyxian
        uses: actions/upload-artifact@v4
        with:
          name: emexDE.ipa
          path: emexDE.ipa
